dev-kick-message: "<gray><b>DevMode</b>\n\n<red>The server is currently under development."
dev-denied-message: "<red>The server is currently under development."

maintenance-kick-message: "<gray><b>DevMode</b>\n\n<red>The server is currently down for maintenance."
maintenance-denied-message: "<red>The server is currently down for maintenance."

default-server: "lobby"